### ISSUE TITLE
Problem to import csv file in odoo using the default behavior

### ISSUE THREAD

**Issue by jcoux** [camptocamp/odoo-dj#109]
Context:

On a project in version 10.0.

We want to import manually a product file (just remove the .log extension - Needed to add the file in github) in odoo interface:
[product.product.csv.log](https://github.com/camptocamp/odoo-dj/files/1815577/product.product.csv.log)

Precision: 

- to import the file in the good menu, we need to activate variants (but I think we can test the problem on any import menu)
- the file contains a specific character: `'      Ø     '`

When we choose the file and load it, we have the following error (before to see the content of the file in interface - Maybe we have other errors later in the feature, I can't see ;) ):

```
2018-03-15 13:29:26,386 1 ERROR odoodb werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/src/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/opt/odoo/src/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/src/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/src/odoo/http.py", line 1314, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/src/odoo/http.py", line 1288, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/src/odoo/http.py", line 1487, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/src/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/src/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/src/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/src/odoo/http.py", line 774, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/src/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/src/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/src/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/src/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/src/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/src/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/src/addons/base_import/controllers/main.py", line 20, in set_file
    'file_type': file.content_type,
  File "/opt/odoo/external-src/odoo-prototype/base_dj/models/base.py", line 222, in write
    self._dj_handle_special_fields_write(vals)
  File "/opt/odoo/external-src/odoo-prototype/base_dj/models/base.py", line 232, in _dj_handle_special_fields_write
    self._dj_handle_file_field_write(fname, info, vals)
  File "/opt/odoo/external-src/odoo-prototype/base_dj/models/base.py", line 236, in _dj_handle_file_field_write
    vals[fname] = self._dj_path_to_file(fname, info, vals[fname])
  File "/opt/odoo/external-src/odoo-prototype/base_dj/models/base.py", line 243, in _dj_path_to_file
    path = to_str(path)
  File "/opt/odoo/external-src/odoo-prototype/base_dj/utils.py", line 123, in to_str
    return s.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 774: ordinal not in range(128)
```

**Comment by simahawk** [comment]
Sorry, but DJ tool is deprecated / not supported anymore on V10.
You can uninstall it.
