### ISSUE TITLE
Missing 'no_reset_password' context key when importing res.users

### ISSUE THREAD

**Issue by grindtildeath** [camptocamp/odoo-dj#89]
When importing `res.users` we should have the context key `{'no_reset_password': 1}` to avoid having the following error :

```
|> version 10.0.0: anthem songs.install.generated.users::main
main...
    Import res.partner from csv...
        Imported 8 records in 'res.partner'
        Imported 8 records in 'res.partner'
    Import res.partner from csv: 1.598s
    load_res_users...
2017-10-17 14:26:20,244 110 ERROR bsfer-56 odoo.addons.mail.models.mail_mail: failed sending mail (id: 3) due to Échec d'envoi du courriel
Échec de l'envoi du courriel via le serveur SMTP  'localhost'.
error: 111
Connection refused
Traceback (most recent call last):
  File "/opt/odoo/src/addons/mail/models/mail_mail.py", line 278, in send
    res = IrMailServer.send_email(msg, mail_server_id=mail.mail_server_id.id)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_mail_server.py", line 464, in send_email
    raise MailDeliveryException(_("Mail Delivery Failed"), msg)
MailDeliveryException: (u"\xc9chec d'envoi du courriel", u"\xc9chec de l'envoi du courriel via le serveur SMTP  'localhost'.\nerror: 111\nConnection refused")
```

**Comment by simahawk** [comment]
fixed and tested on dev branch

**Comment by simahawk** [comment]
merged
